GET http://localhost:5000/api/expression/degs


###
POST http://localhost:5000/api/expression/degtable HTTP/1.1
content-type: application/json

{"validSymbol":["A2M","ACE","ANGPT2","BPI","CD1B","CDR1","EGR2","EGR3","HBEGF","HERPUD1","MCM2","PCTP","PODXL","PPY","PTGS2","RCAN1","SLC4A7","THBD"],"cancerTypeSelected":["KICH","KIRC","KIRP","LUAD","LUSC"],"validColl":["KICH_deg","KIRC_deg","KIRP_deg","LUAD_deg","LUSC_deg"]}


###
# Test server url
POST http://bioinfo.life.hust.edu.cn/GSCA/api/expression/degtable HTTP/1.1
content-type: application/json

{"validSymbol":["A2M","ACE","ANGPT2","BPI","CD1B","CDR1","EGR2","EGR3","HBEGF","HERPUD1","MCM2","PCTP","PODXL","PPY","PTGS2","RCAN1","SLC4A7","THBD"],"cancerTypeSelected":["KICH","KIRC","KIRP","LUAD","LUSC"],"validColl":["KICH_deg","KIRC_deg","KIRP_deg","LUAD_deg","LUSC_deg"]}

###
# deg plot
POST http://localhost:5000/api/expression/degplot HTTP/1.1
content-type: application/json

{"validSymbol":["A2M","ACE","ANGPT2","BPI","CD1B","CDR1","EGR2","EGR3","HBEGF","HERPUD1","MCM2","PCTP","PODXL","PPY","PTGS2","RCAN1","SLC4A7","THBD"],"cancerTypeSelected":["KICH","KIRC","KIRP","LUAD","LUSC"],"validColl":["KICH_deg","KIRC_deg","KIRP_deg","LUAD_deg","LUSC_deg"]}

###
POST http://bioinfo.life.hust.edu.cn/GSCA/api/expression/degplot HTTP/1.1
content-type: application/json

{"validSymbol":["A2M","ACE","ANGPT2","BPI","CD1B","CDR1","EGR2","EGR3","HBEGF","HERPUD1","MCM2","PCTP","PODXL","PPY","PTGS2","RCAN1","SLC4A7","THBD"],"cancerTypeSelected":["KICH","KIRC","KIRP","LUAD","LUSC"],"validColl":["KICH_deg","KIRC_deg","KIRP_deg","LUAD_deg","LUSC_deg"]}