// Generated by https://quicktype.io

export interface CancerStatTableRecord {
  cancer_types: string;
  expr: string;
  survival: string;
  subtype: string;
  stage: string;
  immune: string;
  cnv: string;
  snv: string;
  methy: string;
}
