// Generated by https://quicktype.io

export interface CancerStatTableRecord {
  cancer_types: string;
  expr: string;
  OS: string;
  PFS: string;
  pathologic_stage: string;
  masaoka_stage: string;
  clinical_stage: string;
  igcccg_stage: string;
  subtype: string;
  immune: string;
  cnv: string;
  snv: string;
  methy: string;
}
