// Generated by https://quicktype.io

export interface CancerStatTableRecord {
  cancer_types: string;
  expr: number;
  survival: number;
  stage: number;
  immune: number;
  cnv: number;
  snv: number;
  methy: number;
}
