// Generated by https://quicktype.io

export interface CnvTableRecord {
  entrez: number;
  symbol: string;
  a_total: number;
  d_total: number;
  a_hete: number;
  d_hete: number;
  a_homo: number;
  d_homo: number;
  cancertype: string;
}
