// Generated by https://quicktype.io

export interface DegTableRecord {
  entrez: number;
  symbol: string;
  normal: number;
  tumor: number;
  fc: number;
  pval: number;
  fdr: number;
  n_normal: number;
  n_tumor: number;
  cancertype: string;
}
