// Generated by https://quicktype.io

export interface GSVAStageTableRecord {
  pval: number;
  fdr: number;
  cancertype: string;
  stagetype: string;
  stage1: string;
  stage2: string;
  stage3: string;
  stage4: string;
}
