// Generated by https://quicktype.io

export interface GSVAStageTableRecord {
  trend_p: number;
  diff_p: number;
  trend_score: number;
  cancertype: string;
  stagetype: string;
  StageIII: string;
  StageII: string;
  StageI: string;
  StageIV: string;
}
