// Generated by https://quicktype.io

export interface GSVASubtypeTableRecord {
  diff_p: number;
  cancertype: string;
  Subtype1: string;
  Subtype2: string;
  Subtype3: string;
  Subtype4: string;
  Subtype5: string;
  Subtype6: string;
}
