// Generated by https://quicktype.io

export interface GSVASurvivalTableRecord {
  logrankp: number;
  higher_risk_of_death: string;
  cancertype: string;
  hr_categorical: number;
  sur_type: string;
}
