// Generated by https://quicktype.io

export interface ImmCorTableRecord {
  entrez: number;
  symbol: string;
  cell_type: string;
  cor: number;
  p_value: number;
  fdr: number;
  cancertype: string;
}
