// Generated by https://quicktype.io

export interface MethyTableRecord {
  entrez: number;
  symbol: string;
  fc: number;
  gene_tag: string;
  trend: string;
  pval: number;
  logfdr: number;
  cancertype: string;
}
