// Generated by https://quicktype.io

export interface MethySurvivalTableRecord {
  entrez: number;
  symbol: string;
  log_rank_p: number;
  cox_p: number;
  HR: number;
  higher_risk_of_death: string;
  cancertype: string;
}
