// Generated by https://quicktype.io

export interface SnvGenesetSurvivalTableRecord {
  logrankp: number;
  cox_p: string;
  cancertype: string;
  hr: number;
  sur_type: string;
  higher_risk_of_death: string;
}
