// Generated by https://quicktype.io

export interface SnvTableRecord {
  entrez: number;
  symbol: string;
  EffectiveMut: number;
  percentage: number;
  sample_size: number;
  cancertype: string;
  NonEffectiveMut: number;
}
