// Generated by https://quicktype.io

export interface SnvTableRecord {
  entrez: number;
  symbol: string;
  mutated_sample_size: number;
  percentage: number;
  sample_size: number;
  cancertype: string;
}
