// Generated by https://quicktype.io

export interface SubtypeTableRecord {
  entrez: number;
  symbol: string;
  pval: number;
  cancertype: string;
  Subtype1: string;
  Subtype2: string;
  Subtype3: string;
  Subtype4: string;
  Subtype5: string;
  Subtype6: string;
}
