// Generated by https://quicktype.io

export interface SurvivalTableRecord {
  entrez: number;
  symbol: string;
  logrankp: number;
  higher_risk_of_death: string;
  cancertype: string;
  'hr_categorical(H/L)': number;
  sur_type: string;
}
