// Generated by https://quicktype.io

export interface SurvivalTableRecord {
  entrez: number;
  symbol: string;
  pval: number;
  higher_risk_of_death: string;
  cancertype: string;
  hr: number;
  sur_type: string;
}
