export default [
  {
    name: 'An-Yuan Guo',
    title: 'Ph.D., Professor',
    email: 'guoay@hust.edu.cn',
    avatar: 'guoay.png',
    department1: 'Department of Bioinformatics and Systems Biology',
    department2: 'College of Life Science and Technology',
    department3: 'Huazhong University of Science and Technology, Wuhan 430074 P.R. China',
  },
  {
    name: 'Fei-Fei Hu',
    title: 'Ph.D., Lecturer',
    email: 'hufeifei_huffy@foxmail.com',
    avatar: 'hufeifei.jpg',
    department1: 'Brain Science and Advanced Technology Institute',
    department2: 'College of Medicine',
    department3: 'Wuhan University of Science & Technology, Wuhan 430065 P.R. China',
  },
  // {
  //   name: 'Chun-Jie Liu',
  //   title: 'Ph.D., Postdoc',
  //   email: 'chunjie.sam.liu@gmail.com',
  //   avatar: 'liucj.png',
  //   department1: 'Department of Bioinformatics and Systems Biology',
  //   department2: 'College of Life Science and Technology',
  //   department3: 'Huazhong University of Science and Technology, Wuhan 430074 P.R. China',
  // },
  {
    name: 'Gui-Yan Xie',
    title: 'Ph.D., Candidate',
    email: 'xieguiyan@hust.edu.cn',
    avatar: 'xiegy.png',
    department1: 'Department of Bioinformatics and Systems Biology',
    department2: 'College of Life Science and Technology',
    department3: 'Huazhong University of Science and Technology, Wuhan 430074 P.R. China',
  },
];
