export default [
  {
    cancer_types: 'ACC',
    clinical_stage: '--',
    cnv: '90',
    DFI: '51',
    DSS: '88',
    expr: '79',
    igcccg_stage: '--',
    immune: '79',
    masaoka_stage: '--',
    methy: '81',
    OS: '92',
    pathologic_stage: '90',
    PFS: '92',
    snv: '92',
    subtype: '--',
  },
  {
    cancer_types: 'BLCA',
    clinical_stage: '--',
    cnv: '408',
    DFI: '163',
    DSS: '354',
    expr: '427',
    igcccg_stage: '--',
    immune: '427',
    masaoka_stage: '--',
    methy: '464',
    OS: '410',
    pathologic_stage: '410',
    PFS: '412',
    snv: '411',
    subtype: '215',
  },
  {
    cancer_types: 'BRCA',
    clinical_stage: '--',
    cnv: '1080',
    DFI: '912',
    DSS: '1028',
    expr: '1218',
    igcccg_stage: '--',
    immune: '1218',
    masaoka_stage: '--',
    methy: '813',
    OS: '1096',
    pathologic_stage: '1089',
    PFS: '1096',
    snv: '1026',
    subtype: '837',
  },
  {
    cancer_types: 'CESC',
    clinical_stage: '300',
    cnv: '295',
    DFI: '171',
    DSS: '290',
    expr: '310',
    igcccg_stage: '--',
    immune: '310',
    masaoka_stage: '--',
    methy: '331',
    OS: '307',
    pathologic_stage: '--',
    PFS: '307',
    snv: '291',
    subtype: '--',
  },
  {
    cancer_types: 'CHOL',
    clinical_stage: '--',
    cnv: '36',
    DFI: '25',
    DSS: '41',
    expr: '45',
    igcccg_stage: '--',
    immune: '45',
    masaoka_stage: '--',
    methy: '46',
    OS: '45',
    pathologic_stage: '45',
    PFS: '45',
    snv: '36',
    subtype: '--',
  },
  {
    cancer_types: 'COAD',
    clinical_stage: '--',
    cnv: '451',
    DFI: '182',
    DSS: '420',
    expr: '329',
    igcccg_stage: '--',
    immune: '329',
    masaoka_stage: '--',
    methy: '358',
    OS: '457',
    pathologic_stage: '448',
    PFS: '458',
    snv: '407',
    subtype: '202',
  },
  {
    cancer_types: 'COADREAD',
    clinical_stage: '--',
    cnv: '616',
    DFI: '--',
    DSS: '--',
    expr: '--',
    igcccg_stage: '--',
    immune: '--',
    masaoka_stage: '--',
    methy: '--',
    OS: '--',
    pathologic_stage: '--',
    PFS: '--',
    snv: '--',
    subtype: '--',
  },
  {
    cancer_types: 'CRC',
    clinical_stage: '--',
    cnv: '--',
    DFI: '--',
    DSS: '--',
    expr: '--',
    igcccg_stage: '--',
    immune: '--',
    masaoka_stage: '--',
    methy: '--',
    OS: '--',
    pathologic_stage: '--',
    PFS: '--',
    snv: '--',
    subtype: '--',
  },
  {
    cancer_types: 'DLBC',
    clinical_stage: '42',
    cnv: '48',
    DFI: '25',
    DSS: '43',
    expr: '48',
    igcccg_stage: '--',
    immune: '48',
    masaoka_stage: '--',
    methy: '53',
    OS: '48',
    pathologic_stage: '--',
    PFS: '48',
    snv: '37',
    subtype: '--',
  },
  {
    cancer_types: 'ESCA',
    clinical_stage: '64',
    cnv: '184',
    DFI: '73',
    DSS: '159',
    expr: '196',
    igcccg_stage: '--',
    immune: '196',
    masaoka_stage: '--',
    methy: '212',
    OS: '185',
    pathologic_stage: '163',
    PFS: '185',
    snv: '185',
    subtype: '--',
  },
  {
    cancer_types: 'GBM',
    clinical_stage: '--',
    cnv: '577',
    DFI: '3',
    DSS: '548',
    expr: '174',
    igcccg_stage: '--',
    immune: '174',
    masaoka_stage: '--',
    methy: '162',
    OS: '592',
    pathologic_stage: '--',
    PFS: '596',
    snv: '403',
    subtype: '500',
  },
  {
    cancer_types: 'HNSC',
    clinical_stage: '514',
    cnv: '522',
    DFI: '122',
    DSS: '434',
    expr: '566',
    igcccg_stage: '--',
    immune: '566',
    masaoka_stage: '--',
    methy: '598',
    OS: '526',
    pathologic_stage: '456',
    PFS: '527',
    snv: '509',
    subtype: '92',
  },
  {
    cancer_types: 'KICH',
    clinical_stage: '--',
    cnv: '66',
    DFI: '70',
    DSS: '109',
    expr: '91',
    igcccg_stage: '--',
    immune: '91',
    masaoka_stage: '--',
    methy: '67',
    OS: '112',
    pathologic_stage: '113',
    PFS: '112',
    snv: '66',
    subtype: '--',
  },
  {
    cancer_types: 'KIRC',
    clinical_stage: '--',
    cnv: '528',
    DFI: '112',
    DSS: '470',
    expr: '606',
    igcccg_stage: '--',
    immune: '606',
    masaoka_stage: '--',
    methy: '496',
    OS: '537',
    pathologic_stage: '535',
    PFS: '535',
    snv: '370',
    subtype: '417',
  },
  {
    cancer_types: 'KIRP',
    clinical_stage: '202',
    cnv: '288',
    DFI: '177',
    DSS: '274',
    expr: '323',
    igcccg_stage: '--',
    immune: '323',
    masaoka_stage: '--',
    methy: '336',
    OS: '290',
    pathologic_stage: '261',
    PFS: '289',
    snv: '282',
    subtype: '--',
  },
  {
    cancer_types: 'LAML',
    clinical_stage: '--',
    cnv: '191',
    DFI: '0',
    DSS: '0',
    expr: '173',
    igcccg_stage: '--',
    immune: '173',
    masaoka_stage: '--',
    methy: '194',
    OS: '188',
    pathologic_stage: '--',
    PFS: '0',
    snv: '85',
    subtype: '--',
  },
  {
    cancer_types: 'LGG',
    clinical_stage: '--',
    cnv: '513',
    DFI: '132',
    DSS: '502',
    expr: '534',
    igcccg_stage: '--',
    immune: '534',
    masaoka_stage: '--',
    methy: '551',
    OS: '514',
    pathologic_stage: '--',
    PFS: '514',
    snv: '526',
    subtype: '--',
  },
  {
    cancer_types: 'LIHC',
    clinical_stage: '--',
    cnv: '370',
    DFI: '282',
    DSS: '324',
    expr: '424',
    igcccg_stage: '--',
    immune: '424',
    masaoka_stage: '--',
    methy: '450',
    OS: '376',
    pathologic_stage: '353',
    PFS: '376',
    snv: '365',
    subtype: '--',
  },
  {
    cancer_types: 'LUAD',
    clinical_stage: '--',
    cnv: '516',
    DFI: '278',
    DSS: '442',
    expr: '576',
    igcccg_stage: '--',
    immune: '576',
    masaoka_stage: '--',
    methy: '525',
    OS: '513',
    pathologic_stage: '514',
    PFS: '513',
    snv: '567',
    subtype: '230',
  },
  {
    cancer_types: 'LUSC',
    clinical_stage: '--',
    cnv: '501',
    DFI: '252',
    DSS: '372',
    expr: '554',
    igcccg_stage: '--',
    immune: '554',
    masaoka_stage: '--',
    methy: '432',
    OS: '498',
    pathologic_stage: '500',
    PFS: '499',
    snv: '485',
    subtype: '178',
  },
  {
    cancer_types: 'MESO',
    clinical_stage: '--',
    cnv: '87',
    DFI: '8',
    DSS: '56',
    expr: '87',
    igcccg_stage: '--',
    immune: '87',
    masaoka_stage: '--',
    methy: '89',
    OS: '86',
    pathologic_stage: '87',
    PFS: '84',
    snv: '82',
    subtype: '--',
  },
  {
    cancer_types: 'OV',
    clinical_stage: '576',
    cnv: '579',
    DFI: '277',
    DSS: '535',
    expr: '309',
    igcccg_stage: '--',
    immune: '309',
    masaoka_stage: '--',
    methy: '11',
    OS: '576',
    pathologic_stage: '--',
    PFS: '582',
    snv: '412',
    subtype: '--',
  },
  {
    cancer_types: 'PAAD',
    clinical_stage: '--',
    cnv: '184',
    DFI: '58',
    DSS: '164',
    expr: '183',
    igcccg_stage: '--',
    immune: '183',
    masaoka_stage: '--',
    methy: '207',
    OS: '185',
    pathologic_stage: '183',
    PFS: '185',
    snv: '178',
    subtype: '--',
  },
  {
    cancer_types: 'PCPG',
    clinical_stage: '--',
    cnv: '162',
    DFI: '159',
    DSS: '177',
    expr: '187',
    igcccg_stage: '--',
    immune: '187',
    masaoka_stage: '--',
    methy: '189',
    OS: '179',
    pathologic_stage: '--',
    PFS: '179',
    snv: '184',
    subtype: '--',
  },
  {
    cancer_types: 'PRAD',
    clinical_stage: '--',
    cnv: '492',
    DFI: '337',
    DSS: '495',
    expr: '550',
    igcccg_stage: '--',
    immune: '550',
    masaoka_stage: '--',
    methy: '573',
    OS: '499',
    pathologic_stage: '--',
    PFS: '500',
    snv: '498',
    subtype: '--',
  },
  {
    cancer_types: 'READ',
    clinical_stage: '--',
    cnv: '165',
    DFI: '47',
    DSS: '159',
    expr: '105',
    igcccg_stage: '--',
    immune: '105',
    masaoka_stage: '--',
    methy: '113',
    OS: '169',
    pathologic_stage: '161',
    PFS: '170',
    snv: '149',
    subtype: '68',
  },
  {
    cancer_types: 'SARC',
    clinical_stage: '--',
    cnv: '257',
    DFI: '146',
    DSS: '243',
    expr: '265',
    igcccg_stage: '--',
    immune: '265',
    masaoka_stage: '--',
    methy: '285',
    OS: '261',
    pathologic_stage: '--',
    PFS: '261',
    snv: '239',
    subtype: '--',
  },
  {
    cancer_types: 'SKCM',
    clinical_stage: '--',
    cnv: '367',
    DFI: '0',
    DSS: '429',
    expr: '474',
    igcccg_stage: '--',
    immune: '474',
    masaoka_stage: '--',
    methy: '493',
    OS: '461',
    pathologic_stage: '432',
    PFS: '456',
    snv: '468',
    subtype: '--',
  },
  {
    cancer_types: 'STAD',
    clinical_stage: '--',
    cnv: '441',
    DFI: '225',
    DSS: '368',
    expr: '450',
    igcccg_stage: '--',
    immune: '450',
    masaoka_stage: '--',
    methy: '413',
    OS: '436',
    pathologic_stage: '419',
    PFS: '439',
    snv: '439',
    subtype: '295',
  },
  {
    cancer_types: 'TGCT',
    clinical_stage: '125',
    cnv: '150',
    DFI: '104',
    DSS: '133',
    expr: '156',
    igcccg_stage: '43',
    immune: '156',
    masaoka_stage: '--',
    methy: '158',
    OS: '134',
    pathologic_stage: '127',
    PFS: '134',
    snv: '151',
    subtype: '--',
  },
  {
    cancer_types: 'THCA',
    clinical_stage: '--',
    cnv: '499',
    DFI: '354',
    DSS: '498',
    expr: '572',
    igcccg_stage: '--',
    immune: '572',
    masaoka_stage: '--',
    methy: '588',
    OS: '503',
    pathologic_stage: '501',
    PFS: '507',
    snv: '500',
    subtype: '--',
  },
  {
    cancer_types: 'THYM',
    clinical_stage: '--',
    cnv: '123',
    DFI: '0',
    DSS: '118',
    expr: '122',
    igcccg_stage: '--',
    immune: '122',
    masaoka_stage: '84',
    methy: '128',
    OS: '123',
    pathologic_stage: '--',
    PFS: '123',
    snv: '123',
    subtype: '--',
  },
  {
    cancer_types: 'UCEC',
    clinical_stage: '548',
    cnv: '539',
    DFI: '403',
    DSS: '516',
    expr: '201',
    igcccg_stage: '--',
    immune: '201',
    masaoka_stage: '--',
    methy: '508',
    OS: '547',
    pathologic_stage: '--',
    PFS: '547',
    snv: '531',
    subtype: '232',
  },
  {
    cancer_types: 'UCS',
    clinical_stage: '57',
    cnv: '56',
    DFI: '25',
    DSS: '53',
    expr: '57',
    igcccg_stage: '--',
    immune: '57',
    masaoka_stage: '--',
    methy: '58',
    OS: '57',
    pathologic_stage: '--',
    PFS: '57',
    snv: '57',
    subtype: '--',
  },
  {
    cancer_types: 'UVM',
    clinical_stage: '80',
    cnv: '80',
    DFI: '0',
    DSS: '78',
    expr: '80',
    igcccg_stage: '--',
    immune: '80',
    masaoka_stage: '--',
    methy: '81',
    OS: '80',
    pathologic_stage: '79',
    PFS: '79',
    snv: '80',
    subtype: '--',
  },
];
