export default [
  {
    color: '#C1A72F',
    shortname: 'ACC',
    fullname: 'Adrenocortical carcinoma',
    expr: '79 samples(Tumor:79)',
  },
  {
    color: '#FAD2D9',
    shortname: 'BLCA',
    fullname: 'Bladder Urothelial Carcinoma',
    expr: '427 samples(Tumor:408; Normal:19)',
  },
  {
    color: '#ED2891',
    shortname: 'BRCA',
    fullname: 'Breast invasive carcinoma',
    expr: '1218 samples(Tumor:1104; Normal:114)',
  },
  {
    color: '#F6B667',
    shortname: 'CESC',
    fullname: 'Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    expr: '310 samples(Tumor:307; Normal:3)',
  },
  {
    color: '#104A7F',
    shortname: 'CHOL',
    fullname: 'Cholangiocarcinoma',
    expr: '45 samples(Tumor:36; Normal:9)',
  },
  {
    color: '#9EDDF9',
    shortname: 'COAD',
    fullname: 'Colon adenocarcinoma',
    expr: '329 samples(Tumor:288; Normal:41)',
  },
  {
    color: '#3953A4',
    shortname: 'DLBC',
    fullname: 'Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    expr: '48 samples(Tumor:48)',
  },
  {
    color: '#007EB5',
    shortname: 'ESCA',
    fullname: 'Esophageal carcinoma',
    expr: '196 samples(Tumor:185; Normal:11)',
  },
  {
    color: '#B2509E',
    shortname: 'GBM',
    fullname: 'Glioblastoma multiforme',
    expr: '174 samples(Tumor:169; Normal:5)',
  },
  {
    color: '#97D1A9',
    shortname: 'HNSC',
    fullname: 'Head and Neck squamous cell carcinoma',
    expr: '566 samples(Tumor:522; Normal:44)',
  },
  {
    color: '#ED1C24',
    shortname: 'KICH',
    fullname: 'Kidney Chromophobe',
    expr: '91 samples(Tumor:66; Normal:25)',
  },
  {
    color: '#F8AFB3',
    shortname: 'KIRC',
    fullname: 'Kidney renal clear cell carcinoma',
    expr: '606 samples(Tumor:534; Normal:72)',
  },
  {
    color: '#EA7075',
    shortname: 'KIRP',
    fullname: 'Kidney renal papillary cell carcinoma',
    expr: '323 samples(Tumor:291; Normal:32)',
  },
  {
    color: '#754C29',
    shortname: 'LAML',
    fullname: 'Acute Myeloid Leukemia',
    expr: '173 samples(Tumor:173)',
  },
  {
    color: '#D49DC7',
    shortname: 'LGG',
    fullname: 'Brain Lower Grade Glioma',
    expr: '534 samples(Tumor:534)',
  },
  {
    color: '#CACCDB',
    shortname: 'LIHC',
    fullname: 'Liver hepatocellular carcinoma',
    expr: '424 samples(Tumor:374; Normal:50)',
  },
  {
    color: '#D3C3E0',
    shortname: 'LUAD',
    fullname: 'Lung adenocarcinoma',
    expr: '576 samples(Tumor:517; Normal:59)',
  },
  {
    color: '#A084BD',
    shortname: 'LUSC',
    fullname: 'Lung squamous cell carcinoma',
    expr: '554 samples(Tumor:503; Normal:51)',
  },
  {
    color: '#542C88',
    shortname: 'MESO',
    fullname: 'Mesothelioma',
    expr: '87 samples(Tumor:87)',
  },
  {
    color: '#D97D25',
    shortname: 'OV',
    fullname: 'Ovarian serous cystadenocarcinoma',
    expr: '309 samples(Tumor:309)',
  },
  {
    color: '#6E7BA2',
    shortname: 'PAAD',
    fullname: 'Pancreatic adenocarcinoma',
    expr: '183 samples(Tumor:179; Normal:4)',
  },
  {
    color: '#E8C51D',
    shortname: 'PCPG',
    fullname: 'Pheochromocytoma and Paraganglioma',
    expr: '187 samples(Tumor:184; Normal:3)',
  },
  {
    color: '#7E1918',
    shortname: 'PRAD',
    fullname: 'Prostate adenocarcinoma',
    expr: '550 samples(Tumor:498; Normal:52)',
  },
  {
    color: '#DAF1FC',
    shortname: 'READ',
    fullname: 'Rectum adenocarcinoma',
    expr: '105 samples(Tumor:95; Normal:10)',
  },
  {
    color: '#00A99D',
    shortname: 'SARC',
    fullname: 'Sarcoma',
    expr: '265 samples(Tumor:263; Normal:2)',
  },
  {
    color: '#BBD642',
    shortname: 'SKCM',
    fullname: 'Skin Cutaneous Melanoma',
    expr: '474 samples(Tumor:473; Normal:1)',
  },
  {
    color: '#00AEEF',
    shortname: 'STAD',
    fullname: 'Stomach adenocarcinoma',
    expr: '450 samples(Tumor:415; Normal:35)',
  },
  {
    color: '#BE1E2D',
    shortname: 'TGCT',
    fullname: 'Testicular Germ Cell Tumors',
    expr: '156 samples(Tumor:156)',
  },
  {
    color: '#F9ED32',
    shortname: 'THCA',
    fullname: 'Thyroid carcinoma',
    expr: '572 samples(Tumor:513; Normal:59)',
  },
  {
    color: '#CEAC8F',
    shortname: 'THYM',
    fullname: 'Thymoma',
    expr: '122 samples(Tumor:120; Normal:2)',
  },
  {
    color: '#FBE3C7',
    shortname: 'UCEC',
    fullname: 'Uterine Corpus Endometrial Carcinoma',
    expr: '201 samples(Tumor:177; Normal:24)',
  },
  {
    color: '#F89420',
    shortname: 'UCS',
    fullname: 'Uterine Carcinosarcoma',
    expr: '57 samples(Tumor:57)',
  },
  {
    color: '#009444',
    shortname: 'UVM',
    fullname: 'Uveal Melanoma',
    expr: '80 samples(Tumor:80)',
  },
];
