export default [
  {
    Cancer_type: 'ACC',
    Sample_size: '90',
    File_name: 'ACC.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BLCA',
    Sample_size: '408',
    File_name: 'BLCA.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BRCA',
    Sample_size: '1080',
    File_name: 'BRCA.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CESC',
    Sample_size: '295',
    File_name: 'CESC.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CHOL',
    Sample_size: '36',
    File_name: 'CHOL.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'COAD',
    Sample_size: '451',
    File_name: 'COAD.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'COADREAD',
    Sample_size: '616',
    File_name: 'COADREAD.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'DLBC',
    Sample_size: '48',
    File_name: 'DLBC.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'ESCA',
    Sample_size: '184',
    File_name: 'ESCA.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'GBM',
    Sample_size: '577',
    File_name: 'GBM.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'HNSC',
    Sample_size: '522',
    File_name: 'HNSC.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KICH',
    Sample_size: '66',
    File_name: 'KICH.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRC',
    Sample_size: '528',
    File_name: 'KIRC.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRP',
    Sample_size: '288',
    File_name: 'KIRP.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LAML',
    Sample_size: '191',
    File_name: 'LAML.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LGG',
    Sample_size: '513',
    File_name: 'LGG.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LIHC',
    Sample_size: '370',
    File_name: 'LIHC.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUAD',
    Sample_size: '516',
    File_name: 'LUAD.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUSC',
    Sample_size: '501',
    File_name: 'LUSC.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'MESO',
    Sample_size: '87',
    File_name: 'MESO.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'OV',
    Sample_size: '579',
    File_name: 'OV.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PAAD',
    Sample_size: '184',
    File_name: 'PAAD.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PCPG',
    Sample_size: '162',
    File_name: 'PCPG.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PRAD',
    Sample_size: '492',
    File_name: 'PRAD.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'READ',
    Sample_size: '165',
    File_name: 'READ.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'SARC',
    Sample_size: '257',
    File_name: 'SARC.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'SKCM',
    Sample_size: '367',
    File_name: 'SKCM.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'STAD',
    Sample_size: '441',
    File_name: 'STAD.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'TGCT',
    Sample_size: '150',
    File_name: 'TGCT.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THCA',
    Sample_size: '499',
    File_name: 'THCA.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THYM',
    Sample_size: '123',
    File_name: 'THYM.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCEC',
    Sample_size: '539',
    File_name: 'UCEC.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCS',
    Sample_size: '56',
    File_name: 'UCS.cnv.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UVM',
    Sample_size: '80',
    File_name: 'UVM.cnv.tsv.gz',
    download: 'Download',
  },
];
