export default{
  all_cnv: {
      collnames: ['ACC_all_cnv', 'BLCA_all_cnv', 'BRCA_all_cnv', 'CESC_all_cnv', 'CHOL_all_cnv', 'COAD_all_cnv', 'COADREAD_all_cnv', 'DLBC_all_cnv', 'ESCA_all_cnv', 'GBM_all_cnv', 'HNSC_all_cnv', 'KICH_all_cnv', 'KIRC_all_cnv', 'KIRP_all_cnv', 'LAML_all_cnv', 'LGG_all_cnv', 'LIHC_all_cnv', 'LUAD_all_cnv', 'LUSC_all_cnv', 'MESO_all_cnv', 'OV_all_cnv', 'PAAD_all_cnv', 'PCPG_all_cnv', 'PRAD_all_cnv', 'READ_all_cnv', 'SARC_all_cnv', 'SKCM_all_cnv', 'STAD_all_cnv', 'TGCT_all_cnv', 'THCA_all_cnv', 'THYM_all_cnv', 'UCEC_all_cnv', 'UCS_all_cnv', 'UVM_all_cnv'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'COADREAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LAML', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  all_expr: {
      collnames: ['ACC_all_expr', 'BLCA_all_expr', 'BRCA_all_expr', 'CESC_all_expr', 'CHOL_all_expr', 'COAD_all_expr', 'DLBC_all_expr', 'ESCA_all_expr', 'GBM_all_expr', 'HNSC_all_expr', 'KICH_all_expr', 'KIRC_all_expr', 'KIRP_all_expr', 'LAML_all_expr', 'LGG_all_expr', 'LIHC_all_expr', 'LUAD_all_expr', 'LUSC_all_expr', 'MESO_all_expr', 'OV_all_expr', 'PAAD_all_expr', 'PCPG_all_expr', 'PRAD_all_expr', 'READ_all_expr', 'SARC_all_expr', 'SKCM_all_expr', 'STAD_all_expr', 'TGCT_all_expr', 'THCA_all_expr', 'THYM_all_expr', 'UCEC_all_expr', 'UCS_all_expr', 'UVM_all_expr'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LAML', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  all_immune: {
      collnames: ['ACC_all_immune', 'BLCA_all_immune', 'BRCA_all_immune', 'CESC_all_immune', 'CHOL_all_immune', 'COAD_all_immune', 'DLBC_all_immune', 'ESCA_all_immune', 'GBM_all_immune', 'HNSC_all_immune', 'KICH_all_immune', 'KIRC_all_immune', 'KIRP_all_immune', 'LAML_all_immune', 'LGG_all_immune', 'LIHC_all_immune', 'LUAD_all_immune', 'LUSC_all_immune', 'MESO_all_immune', 'OV_all_immune', 'PAAD_all_immune', 'PCPG_all_immune', 'PRAD_all_immune', 'READ_all_immune', 'SARC_all_immune', 'SKCM_all_immune', 'STAD_all_immune', 'TGCT_all_immune', 'THCA_all_immune', 'THYM_all_immune', 'UCEC_all_immune', 'UCS_all_immune', 'UVM_all_immune'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LAML', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  all_methy: {
      collnames: ['ACC_all_methy', 'BLCA_all_methy', 'BRCA_all_methy', 'CESC_all_methy', 'CHOL_all_methy', 'COAD_all_methy', 'DLBC_all_methy', 'ESCA_all_methy', 'GBM_all_methy', 'HNSC_all_methy', 'KICH_all_methy', 'KIRC_all_methy', 'KIRP_all_methy', 'LAML_all_methy', 'LGG_all_methy', 'LIHC_all_methy', 'LUAD_all_methy', 'LUSC_all_methy', 'MESO_all_methy', 'OV_all_methy', 'PAAD_all_methy', 'PCPG_all_methy', 'PRAD_all_methy', 'READ_all_methy', 'SARC_all_methy', 'SKCM_all_methy', 'STAD_all_methy', 'TGCT_all_methy', 'THCA_all_methy', 'THYM_all_methy', 'UCEC_all_methy', 'UCS_all_methy', 'UVM_all_methy'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LAML', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  cnv_cor_expr: {
      collnames: ['ACC_cnv_cor_expr', 'BLCA_cnv_cor_expr', 'BRCA_cnv_cor_expr', 'CESC_cnv_cor_expr', 'CHOL_cnv_cor_expr', 'COAD_cnv_cor_expr', 'DLBC_cnv_cor_expr', 'ESCA_cnv_cor_expr', 'GBM_cnv_cor_expr', 'HNSC_cnv_cor_expr', 'KICH_cnv_cor_expr', 'KIRC_cnv_cor_expr', 'KIRP_cnv_cor_expr', 'LAML_cnv_cor_expr', 'LGG_cnv_cor_expr', 'LIHC_cnv_cor_expr', 'LUAD_cnv_cor_expr', 'LUSC_cnv_cor_expr', 'MESO_cnv_cor_expr', 'OV_cnv_cor_expr', 'PAAD_cnv_cor_expr', 'PCPG_cnv_cor_expr', 'PRAD_cnv_cor_expr', 'READ_cnv_cor_expr', 'SARC_cnv_cor_expr', 'SKCM_cnv_cor_expr', 'STAD_cnv_cor_expr', 'TGCT_cnv_cor_expr', 'THCA_cnv_cor_expr', 'THYM_cnv_cor_expr', 'UCEC_cnv_cor_expr', 'UCS_cnv_cor_expr', 'UVM_cnv_cor_expr'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LAML', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  cnv_percent: {
      collnames: ['ACC_cnv_percent', 'BLCA_cnv_percent', 'BRCA_cnv_percent', 'CESC_cnv_percent', 'CHOL_cnv_percent', 'COAD_cnv_percent', 'COADREAD_cnv_percent', 'DLBC_cnv_percent', 'ESCA_cnv_percent', 'GBM_cnv_percent', 'HNSC_cnv_percent', 'KICH_cnv_percent', 'KIRC_cnv_percent', 'KIRP_cnv_percent', 'LAML_cnv_percent', 'LGG_cnv_percent', 'LIHC_cnv_percent', 'LUAD_cnv_percent', 'LUSC_cnv_percent', 'MESO_cnv_percent', 'OV_cnv_percent', 'PAAD_cnv_percent', 'PCPG_cnv_percent', 'PRAD_cnv_percent', 'READ_cnv_percent', 'SARC_cnv_percent', 'SKCM_cnv_percent', 'STAD_cnv_percent', 'TGCT_cnv_percent', 'THCA_cnv_percent', 'THYM_cnv_percent', 'UCEC_cnv_percent', 'UCS_cnv_percent', 'UVM_cnv_percent'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'COADREAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LAML', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  cnv_threshold: {
      collnames: ['ACC_cnv_threshold', 'BLCA_cnv_threshold', 'BRCA_cnv_threshold', 'CESC_cnv_threshold', 'CHOL_cnv_threshold', 'COAD_cnv_threshold', 'COADREAD_cnv_threshold', 'DLBC_cnv_threshold', 'ESCA_cnv_threshold', 'GBM_cnv_threshold', 'HNSC_cnv_threshold', 'KICH_cnv_threshold', 'KIRC_cnv_threshold', 'KIRP_cnv_threshold', 'LAML_cnv_threshold', 'LGG_cnv_threshold', 'LIHC_cnv_threshold', 'LUAD_cnv_threshold', 'LUSC_cnv_threshold', 'MESO_cnv_threshold', 'OV_cnv_threshold', 'PAAD_cnv_threshold', 'PCPG_cnv_threshold', 'PRAD_cnv_threshold', 'READ_cnv_threshold', 'SARC_cnv_threshold', 'SKCM_cnv_threshold', 'STAD_cnv_threshold', 'TGCT_cnv_threshold', 'THCA_cnv_threshold', 'THYM_cnv_threshold', 'UCEC_cnv_threshold', 'UCS_cnv_threshold', 'UVM_cnv_threshold'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'COADREAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LAML', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  deg: {
      collnames: ['BLCA_deg', 'BRCA_deg', 'COAD_deg', 'ESCA_deg', 'HNSC_deg', 'KICH_deg', 'KIRC_deg', 'KIRP_deg', 'LIHC_deg', 'LUAD_deg', 'LUSC_deg', 'PRAD_deg', 'STAD_deg', 'THCA_deg'],
      cancertypes: ['BLCA', 'BRCA', 'COAD', 'ESCA', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LIHC', 'LUAD', 'LUSC', 'PRAD', 'STAD', 'THCA'],
    },
  expr_stage: {
      collnames: ['ACC_expr_stage', 'BLCA_expr_stage', 'BRCA_expr_stage', 'CESC_expr_stage', 'CHOL_expr_stage', 'COAD_expr_stage', 'DLBC_expr_stage', 'ESCA_expr_stage', 'HNSC_expr_stage', 'KICH_expr_stage', 'KIRC_expr_stage', 'KIRP_expr_stage', 'LIHC_expr_stage', 'LUAD_expr_stage', 'LUSC_expr_stage', 'MESO_expr_stage', 'PAAD_expr_stage', 'READ_expr_stage', 'SKCM_expr_stage', 'STAD_expr_stage', 'TGCT_expr_stage', 'THCA_expr_stage', 'UCEC_expr_stage', 'UCS_expr_stage', 'UVM_expr_stage'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'DLBC', 'ESCA', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'PAAD', 'READ', 'SKCM', 'STAD', 'TGCT', 'THCA', 'UCEC', 'UCS', 'UVM'],
    },
  expr_subtype: {
      collnames: ['BLCA_expr_subtype', 'BRCA_expr_subtype', 'HNSC_expr_subtype', 'KIRC_expr_subtype', 'LUAD_expr_subtype', 'LUSC_expr_subtype', 'STAD_expr_subtype'],
      cancertypes: ['BLCA', 'BRCA', 'HNSC', 'KIRC', 'LUAD', 'LUSC', 'STAD'],
    },
  expr_survival: {
      collnames: ['ACC_expr_survival', 'BLCA_expr_survival', 'BRCA_expr_survival', 'CESC_expr_survival', 'COAD_expr_survival', 'DLBC_expr_survival', 'ESCA_expr_survival', 'GBM_expr_survival', 'HNSC_expr_survival', 'KICH_expr_survival', 'KIRC_expr_survival', 'KIRP_expr_survival', 'LGG_expr_survival', 'LIHC_expr_survival', 'LUAD_expr_survival', 'LUSC_expr_survival', 'MESO_expr_survival', 'OV_expr_survival', 'PAAD_expr_survival', 'PCPG_expr_survival', 'PRAD_expr_survival', 'READ_expr_survival', 'SARC_expr_survival', 'SKCM_expr_survival', 'STAD_expr_survival', 'TGCT_expr_survival', 'THCA_expr_survival', 'THYM_expr_survival', 'UCEC_expr_survival', 'UCS_expr_survival', 'UVM_expr_survival'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'COAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  immune_cor_expr: {
      collnames: ['ACC_immune_cor_expr', 'BLCA_immune_cor_expr', 'BRCA_immune_cor_expr', 'CESC_immune_cor_expr', 'CHOL_immune_cor_expr', 'COAD_immune_cor_expr', 'DLBC_immune_cor_expr', 'ESCA_immune_cor_expr', 'GBM_immune_cor_expr', 'HNSC_immune_cor_expr', 'KICH_immune_cor_expr', 'KIRC_immune_cor_expr', 'KIRP_immune_cor_expr', 'LAML_immune_cor_expr', 'LGG_immune_cor_expr', 'LIHC_immune_cor_expr', 'LUAD_immune_cor_expr', 'LUSC_immune_cor_expr', 'MESO_immune_cor_expr', 'OV_immune_cor_expr', 'PAAD_immune_cor_expr', 'PCPG_immune_cor_expr', 'PRAD_immune_cor_expr', 'READ_immune_cor_expr', 'SARC_immune_cor_expr', 'SKCM_immune_cor_expr', 'STAD_immune_cor_expr', 'TGCT_immune_cor_expr', 'THCA_immune_cor_expr', 'THYM_immune_cor_expr', 'UCEC_immune_cor_expr', 'UCS_immune_cor_expr', 'UVM_immune_cor_expr'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LAML', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  immune_cor_methy: {
      collnames: ['ACC_immune_cor_methy', 'BLCA_immune_cor_methy', 'BRCA_immune_cor_methy', 'CESC_immune_cor_methy', 'CHOL_immune_cor_methy', 'COAD_immune_cor_methy', 'DLBC_immune_cor_methy', 'ESCA_immune_cor_methy', 'GBM_immune_cor_methy', 'HNSC_immune_cor_methy', 'KICH_immune_cor_methy', 'KIRC_immune_cor_methy', 'KIRP_immune_cor_methy', 'LAML_immune_cor_methy', 'LGG_immune_cor_methy', 'LIHC_immune_cor_methy', 'LUAD_immune_cor_methy', 'LUSC_immune_cor_methy', 'MESO_immune_cor_methy', 'OV_immune_cor_methy', 'PAAD_immune_cor_methy', 'PCPG_immune_cor_methy', 'PRAD_immune_cor_methy', 'READ_immune_cor_methy', 'SARC_immune_cor_methy', 'SKCM_immune_cor_methy', 'STAD_immune_cor_methy', 'TGCT_immune_cor_methy', 'THCA_immune_cor_methy', 'THYM_immune_cor_methy', 'UCEC_immune_cor_methy', 'UCS_immune_cor_methy', 'UVM_immune_cor_methy'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LAML', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  methy_cor_expr: {
      collnames: ['ACC_methy_cor_expr', 'BLCA_methy_cor_expr', 'BRCA_methy_cor_expr', 'CESC_methy_cor_expr', 'CHOL_methy_cor_expr', 'COAD_methy_cor_expr', 'DLBC_methy_cor_expr', 'ESCA_methy_cor_expr', 'GBM_methy_cor_expr', 'HNSC_methy_cor_expr', 'KICH_methy_cor_expr', 'KIRC_methy_cor_expr', 'KIRP_methy_cor_expr', 'LAML_methy_cor_expr', 'LGG_methy_cor_expr', 'LIHC_methy_cor_expr', 'LUAD_methy_cor_expr', 'LUSC_methy_cor_expr', 'MESO_methy_cor_expr', 'OV_methy_cor_expr', 'PAAD_methy_cor_expr', 'PCPG_methy_cor_expr', 'PRAD_methy_cor_expr', 'READ_methy_cor_expr', 'SARC_methy_cor_expr', 'SKCM_methy_cor_expr', 'STAD_methy_cor_expr', 'TGCT_methy_cor_expr', 'THCA_methy_cor_expr', 'THYM_methy_cor_expr', 'UCEC_methy_cor_expr', 'UCS_methy_cor_expr', 'UVM_methy_cor_expr'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LAML', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  methy_diff: {
      collnames: ['BLCA_methy_diff', 'BRCA_methy_diff', 'COAD_methy_diff', 'ESCA_methy_diff', 'HNSC_methy_diff', 'KIRC_methy_diff', 'KIRP_methy_diff', 'LIHC_methy_diff', 'LUAD_methy_diff', 'LUSC_methy_diff', 'PAAD_methy_diff', 'PRAD_methy_diff', 'THCA_methy_diff', 'UCEC_methy_diff'],
      cancertypes: ['BLCA', 'BRCA', 'COAD', 'ESCA', 'HNSC', 'KIRC', 'KIRP', 'LIHC', 'LUAD', 'LUSC', 'PAAD', 'PRAD', 'THCA', 'UCEC'],
    },
  methy_survival: {
      collnames: ['ACC_methy_survival', 'BLCA_methy_survival', 'BRCA_methy_survival', 'CESC_methy_survival', 'CHOL_methy_survival', 'COAD_methy_survival', 'DLBC_methy_survival', 'ESCA_methy_survival', 'GBM_methy_survival', 'HNSC_methy_survival', 'KICH_methy_survival', 'KIRC_methy_survival', 'KIRP_methy_survival', 'LAML_methy_survival', 'LGG_methy_survival', 'LIHC_methy_survival', 'LUAD_methy_survival', 'LUSC_methy_survival', 'MESO_methy_survival', 'OV_methy_survival', 'PAAD_methy_survival', 'PCPG_methy_survival', 'PRAD_methy_survival', 'READ_methy_survival', 'SARC_methy_survival', 'SKCM_methy_survival', 'STAD_methy_survival', 'TGCT_methy_survival', 'THCA_methy_survival', 'THYM_methy_survival', 'UCEC_methy_survival', 'UCS_methy_survival', 'UVM_methy_survival'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LAML', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  rppa_diff: {
      collnames: ['ACC_rppa_diff', 'BLCA_rppa_diff', 'BRCA_rppa_diff', 'CESC_rppa_diff', 'CHOL_rppa_diff', 'COAD_rppa_diff', 'DLBC_rppa_diff', 'ESCA_rppa_diff', 'GBM_rppa_diff', 'HNSC_rppa_diff', 'KICH_rppa_diff', 'KIRC_rppa_diff', 'KIRP_rppa_diff', 'LGG_rppa_diff', 'LIHC_rppa_diff', 'LUAD_rppa_diff', 'LUSC_rppa_diff', 'MESO_rppa_diff', 'OV_rppa_diff', 'PAAD_rppa_diff', 'PCPG_rppa_diff', 'PRAD_rppa_diff', 'READ_rppa_diff', 'SARC_rppa_diff', 'SKCM_rppa_diff', 'STAD_rppa_diff', 'TGCT_rppa_diff', 'THCA_rppa_diff', 'THYM_rppa_diff', 'UCEC_rppa_diff', 'UCS_rppa_diff', 'UVM_rppa_diff'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  snv_count: {
      collnames: ['ACC_snv_count', 'BLCA_snv_count', 'BRCA_snv_count', 'CESC_snv_count', 'CHOL_snv_count', 'COAD_snv_count', 'DLBC_snv_count', 'ESCA_snv_count', 'GBM_snv_count', 'HNSC_snv_count', 'KICH_snv_count', 'KIRC_snv_count', 'KIRP_snv_count', 'LAML_snv_count', 'LGG_snv_count', 'LIHC_snv_count', 'LUAD_snv_count', 'LUSC_snv_count', 'MESO_snv_count', 'OV_snv_count', 'PAAD_snv_count', 'PCPG_snv_count', 'PRAD_snv_count', 'READ_snv_count', 'SARC_snv_count', 'SKCM_snv_count', 'STAD_snv_count', 'TGCT_snv_count', 'THCA_snv_count', 'THYM_snv_count', 'UCEC_snv_count', 'UCS_snv_count', 'UVM_snv_count'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LAML', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
  snv_maf: {
      collnames: ['BLCA_snv_maf', 'BRCA_snv_maf', 'CESC_snv_maf', 'ESCA_snv_maf', 'GBM_snv_maf', 'KIRP_snv_maf', 'LIHC_snv_maf', 'LUAD_snv_maf', 'LUSC_snv_maf', 'MESO_snv_maf', 'OV_snv_maf', 'PAAD_snv_maf', 'PRAD_snv_maf', 'SARC_snv_maf', 'TGCT_snv_maf', 'THYM_snv_maf', 'UCEC_snv_maf'],
      cancertypes: ['BLCA', 'BRCA', 'CESC', 'ESCA', 'GBM', 'KIRP', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PRAD', 'SARC', 'TGCT', 'THYM', 'UCEC'],
    },
  snv_survival: {
      collnames: ['ACC_snv_survival', 'BLCA_snv_survival', 'BRCA_snv_survival', 'CESC_snv_survival', 'CHOL_snv_survival', 'COAD_snv_survival', 'DLBC_snv_survival', 'ESCA_snv_survival', 'GBM_snv_survival', 'HNSC_snv_survival', 'KICH_snv_survival', 'KIRC_snv_survival', 'KIRP_snv_survival', 'LAML_snv_survival', 'LGG_snv_survival', 'LIHC_snv_survival', 'LUAD_snv_survival', 'LUSC_snv_survival', 'MESO_snv_survival', 'OV_snv_survival', 'PAAD_snv_survival', 'PCPG_snv_survival', 'PRAD_snv_survival', 'READ_snv_survival', 'SARC_snv_survival', 'SKCM_snv_survival', 'STAD_snv_survival', 'TGCT_snv_survival', 'THCA_snv_survival', 'THYM_snv_survival', 'UCEC_snv_survival', 'UCS_snv_survival', 'UVM_snv_survival'],
      cancertypes: ['ACC', 'BLCA', 'BRCA', 'CESC', 'CHOL', 'COAD', 'DLBC', 'ESCA', 'GBM', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LAML', 'LGG', 'LIHC', 'LUAD', 'LUSC', 'MESO', 'OV', 'PAAD', 'PCPG', 'PRAD', 'READ', 'SARC', 'SKCM', 'STAD', 'TGCT', 'THCA', 'THYM', 'UCEC', 'UCS', 'UVM'],
    },
};