export default [
  {
    Immuneabbreviation: 'DC',
    fullname: 'Dendritic cells',
  },
  { Immuneabbreviation: 'Bcell', fullname: 'B cell' },
  { Immuneabbreviation: 'Monocyte', fullname: 'Monocyte' },
  { Immuneabbreviation: 'Macrophage', fullname: 'Macrophage' },
  { Immuneabbreviation: 'NK', fullname: 'NK' },
  { Immuneabbreviation: 'Neutrophil', fullname: 'Neutrophil' },
  { Immuneabbreviation: 'CD4_T', fullname: 'CD4 T cell' },
  { Immuneabbreviation: 'CD8_T', fullname: 'CD8 T cell' },
  { Immuneabbreviation: 'NKT', fullname: 'Natural killer T cell' },
  { Immuneabbreviation: 'Gamma_delta', fullname: 'Gamma delta T cell' },
  { Immuneabbreviation: 'CD4_naive', fullname: 'CD4 naïve T cell' },
  { Immuneabbreviation: 'CD8_naive', fullname: 'CD8 naïve T cell' },
  { Immuneabbreviation: 'Cytotoxic', fullname: 'Cytotoxic T cell' },
  { Immuneabbreviation: 'Exhausted', fullname: 'Exhausted T cell' },
  { Immuneabbreviation: 'Tr1', fullname: 'Type 1 regulatory T cell' },
  { Immuneabbreviation: 'nTreg', fullname: 'Natural Treg' },
  { Immuneabbreviation: 'iTreg', fullname: 'Induced regulatory T cell' },
  { Immuneabbreviation: 'Th1', fullname: 'T helper type 1' },
  { Immuneabbreviation: 'Th2', fullname: 'T helper type 2' },
  { Immuneabbreviation: 'Th17', fullname: 'T helper type 17' },
  { Immuneabbreviation: 'Tfh', fullname: 'T follicular helper cell' },
  { Immuneabbreviation: 'Central_memory', fullname: 'Central memory T cell' },
  { Immuneabbreviation: 'Effector_memory', fullname: 'Effector memory T cell' },
  { Immuneabbreviation: 'MAIT', fullname: 'Mucosal associated invariant T cell' },
  { Immuneabbreviation: 'InfiltrationScore', fullname: 'Overall infiltration score of 24 immune cells' },
];
