export default [
  {
    Cancer_type: 'ACC',
    Sample_size: '81',
    File_name: 'ACC.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BLCA',
    Sample_size: '464',
    File_name: 'BLCA.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BRCA',
    Sample_size: '813',
    File_name: 'BRCA.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CESC',
    Sample_size: '331',
    File_name: 'CESC.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CHOL',
    Sample_size: '46',
    File_name: 'CHOL.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'COAD',
    Sample_size: '358',
    File_name: 'COAD.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'DLBC',
    Sample_size: '53',
    File_name: 'DLBC.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'ESCA',
    Sample_size: '212',
    File_name: 'ESCA.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'GBM',
    Sample_size: '162',
    File_name: 'GBM.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'HNSC',
    Sample_size: '598',
    File_name: 'HNSC.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KICH',
    Sample_size: '67',
    File_name: 'KICH.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRC',
    Sample_size: '496',
    File_name: 'KIRC.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRP',
    Sample_size: '336',
    File_name: 'KIRP.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LAML',
    Sample_size: '194',
    File_name: 'LAML.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LGG',
    Sample_size: '551',
    File_name: 'LGG.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LIHC',
    Sample_size: '450',
    File_name: 'LIHC.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUAD',
    Sample_size: '525',
    File_name: 'LUAD.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUSC',
    Sample_size: '432',
    File_name: 'LUSC.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'MESO',
    Sample_size: '89',
    File_name: 'MESO.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'OV',
    Sample_size: '11',
    File_name: 'OV.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PAAD',
    Sample_size: '207',
    File_name: 'PAAD.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PCPG',
    Sample_size: '189',
    File_name: 'PCPG.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PRAD',
    Sample_size: '573',
    File_name: 'PRAD.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'READ',
    Sample_size: '113',
    File_name: 'READ.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'SARC',
    Sample_size: '285',
    File_name: 'SARC.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'SKCM',
    Sample_size: '493',
    File_name: 'SKCM.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'STAD',
    Sample_size: '413',
    File_name: 'STAD.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'TGCT',
    Sample_size: '158',
    File_name: 'TGCT.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THCA',
    Sample_size: '588',
    File_name: 'THCA.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THYM',
    Sample_size: '128',
    File_name: 'THYM.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCEC',
    Sample_size: '508',
    File_name: 'UCEC.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCS',
    Sample_size: '58',
    File_name: 'UCS.methy.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UVM',
    Sample_size: '81',
    File_name: 'UVM.methy.tsv.gz',
    download: 'Download',
  },
];
