export default [
  {
    Cancer_type: 'ACC',
    Sample_size: '79',
    File_name: 'ACC.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BLCA',
    Sample_size: '427',
    File_name: 'BLCA.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BRCA',
    Sample_size: '1218',
    File_name: 'BRCA.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CESC',
    Sample_size: '310',
    File_name: 'CESC.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CHOL',
    Sample_size: '45',
    File_name: 'CHOL.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'COAD',
    Sample_size: '329',
    File_name: 'COAD.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'DLBC',
    Sample_size: '48',
    File_name: 'DLBC.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'ESCA',
    Sample_size: '196',
    File_name: 'ESCA.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'GBM',
    Sample_size: '174',
    File_name: 'GBM.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'HNSC',
    Sample_size: '566',
    File_name: 'HNSC.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KICH',
    Sample_size: '91',
    File_name: 'KICH.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRC',
    Sample_size: '606',
    File_name: 'KIRC.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRP',
    Sample_size: '323',
    File_name: 'KIRP.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LAML',
    Sample_size: '173',
    File_name: 'LAML.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LGG',
    Sample_size: '534',
    File_name: 'LGG.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LIHC',
    Sample_size: '424',
    File_name: 'LIHC.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUAD',
    Sample_size: '576',
    File_name: 'LUAD.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUSC',
    Sample_size: '554',
    File_name: 'LUSC.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'MESO',
    Sample_size: '87',
    File_name: 'MESO.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'OV',
    Sample_size: '309',
    File_name: 'OV.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PAAD',
    Sample_size: '183',
    File_name: 'PAAD.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PCPG',
    Sample_size: '187',
    File_name: 'PCPG.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PRAD',
    Sample_size: '550',
    File_name: 'PRAD.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'READ',
    Sample_size: '105',
    File_name: 'READ.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'SARC',
    Sample_size: '265',
    File_name: 'SARC.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'SKCM',
    Sample_size: '474',
    File_name: 'SKCM.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'STAD',
    Sample_size: '450',
    File_name: 'STAD.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'TGCT',
    Sample_size: '156',
    File_name: 'TGCT.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THCA',
    Sample_size: '572',
    File_name: 'THCA.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THYM',
    Sample_size: '122',
    File_name: 'THYM.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCEC',
    Sample_size: '201',
    File_name: 'UCEC.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCS',
    Sample_size: '57',
    File_name: 'UCS.mRNA_expr.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UVM',
    Sample_size: '80',
    File_name: 'UVM.mRNA_expr.tsv.gz',
    download: 'Download',
  },
];
