export default [
  {
    Cancer_type: 'LGG',
    Sample_size: '429',
    File_name: 'LGG.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUAD',
    Sample_size: '365',
    File_name: 'LUAD.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PCPG',
    Sample_size: '80',
    File_name: 'PCPG.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'TGCT',
    Sample_size: '118',
    File_name: 'TGCT.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'SKCM',
    Sample_size: '354',
    File_name: 'SKCM.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'COAD',
    Sample_size: '362',
    File_name: 'COAD.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PRAD',
    Sample_size: '352',
    File_name: 'PRAD.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'SARC',
    Sample_size: '223',
    File_name: 'SARC.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'OV',
    Sample_size: '425',
    File_name: 'OV.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UVM',
    Sample_size: '12',
    File_name: 'UVM.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'ACC',
    Sample_size: '46',
    File_name: 'ACC.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'GBM',
    Sample_size: '233',
    File_name: 'GBM.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCEC',
    Sample_size: '440',
    File_name: 'UCEC.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BLCA',
    Sample_size: '344',
    File_name: 'BLCA.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUSC',
    Sample_size: '328',
    File_name: 'LUSC.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KICH',
    Sample_size: '63',
    File_name: 'KICH.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'READ',
    Sample_size: '131',
    File_name: 'READ.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'MESO',
    Sample_size: '63',
    File_name: 'MESO.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THYM',
    Sample_size: '90',
    File_name: 'THYM.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CESC',
    Sample_size: '173',
    File_name: 'CESC.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LIHC',
    Sample_size: '184',
    File_name: 'LIHC.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THCA',
    Sample_size: '372',
    File_name: 'THCA.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'HNSC',
    Sample_size: '357',
    File_name: 'HNSC.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'STAD',
    Sample_size: '392',
    File_name: 'STAD.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'ESCA',
    Sample_size: '126',
    File_name: 'ESCA.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BRCA',
    Sample_size: '887',
    File_name: 'BRCA.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'DLBC',
    Sample_size: '33',
    File_name: 'DLBC.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CHOL',
    Sample_size: '30',
    File_name: 'CHOL.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCS',
    Sample_size: '48',
    File_name: 'UCS.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRC',
    Sample_size: '478',
    File_name: 'KIRC.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRP',
    Sample_size: '215',
    File_name: 'KIRP.PAS.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PAAD',
    Sample_size: '123',
    File_name: 'PAAD.PAS.tsv.gz',
    download: 'Download',
  },
];
