export default [
  {
    Cancer_type: 'ACC',
    Sample_size: '92',
    File_name: 'ACC_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BLCA',
    Sample_size: '411',
    File_name: 'BLCA_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BRCA',
    Sample_size: '1026',
    File_name: 'BRCA_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CESC',
    Sample_size: '291',
    File_name: 'CESC_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CHOL',
    Sample_size: '36',
    File_name: 'CHOL_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'COAD',
    Sample_size: '407',
    File_name: 'COAD_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'DLBC',
    Sample_size: '37',
    File_name: 'DLBC_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'ESCA',
    Sample_size: '185',
    File_name: 'ESCA_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'GBM',
    Sample_size: '403',
    File_name: 'GBM_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'HNSC',
    Sample_size: '509',
    File_name: 'HNSC_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KICH',
    Sample_size: '66',
    File_name: 'KICH_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRC',
    Sample_size: '370',
    File_name: 'KIRC_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRP',
    Sample_size: '282',
    File_name: 'KIRP_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LAML',
    Sample_size: '85',
    File_name: 'LAML_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LGG',
    Sample_size: '526',
    File_name: 'LGG_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LIHC',
    Sample_size: '365',
    File_name: 'LIHC_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUAD',
    Sample_size: '567',
    File_name: 'LUAD_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUSC',
    Sample_size: '485',
    File_name: 'LUSC_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'MESO',
    Sample_size: '82',
    File_name: 'MESO_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'OV',
    Sample_size: '412',
    File_name: 'OV_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PAAD',
    Sample_size: '178',
    File_name: 'PAAD_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PCPG',
    Sample_size: '184',
    File_name: 'PCPG_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PRAD',
    Sample_size: '498',
    File_name: 'PRAD_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'READ',
    Sample_size: '149',
    File_name: 'READ_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'SARC',
    Sample_size: '239',
    File_name: 'SARC_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'SKCM',
    Sample_size: '468',
    File_name: 'SKCM_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'STAD',
    Sample_size: '439',
    File_name: 'STAD_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'TGCT',
    Sample_size: '151',
    File_name: 'TGCT_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THCA',
    Sample_size: '500',
    File_name: 'THCA_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THYM',
    Sample_size: '123',
    File_name: 'THYM_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCEC',
    Sample_size: '531',
    File_name: 'UCEC_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCS',
    Sample_size: '57',
    File_name: 'UCS_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UVM',
    Sample_size: '80',
    File_name: 'UVM_maf_data.IdTrans.tsv.gz',
    download: 'Download',
  },
];
