export default [
  {
    Cancer_type: 'ACC',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:90',
    File_name: 'ACC.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BLCA',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:410',
    File_name: 'BLCA.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BRCA',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:1089',
    File_name: 'BRCA.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CESC',
    Sample_size: 'clinical_stage:300; igcccg_stage:--; masaoka_stage:--; pathologic_stage:--',
    File_name: 'CESC.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CHOL',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:45',
    File_name: 'CHOL.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'COAD',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:448',
    File_name: 'COAD.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'DLBC',
    Sample_size: 'clinical_stage:42; igcccg_stage:--; masaoka_stage:--; pathologic_stage:--',
    File_name: 'DLBC.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'ESCA',
    Sample_size: 'clinical_stage:64; igcccg_stage:--; masaoka_stage:--; pathologic_stage:163',
    File_name: 'ESCA.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'HNSC',
    Sample_size: 'clinical_stage:514; igcccg_stage:--; masaoka_stage:--; pathologic_stage:456',
    File_name: 'HNSC.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KICH',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:113',
    File_name: 'KICH.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRC',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:535',
    File_name: 'KIRC.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRP',
    Sample_size: 'clinical_stage:202; igcccg_stage:--; masaoka_stage:--; pathologic_stage:261',
    File_name: 'KIRP.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LIHC',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:353',
    File_name: 'LIHC.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUAD',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:514',
    File_name: 'LUAD.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUSC',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:500',
    File_name: 'LUSC.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'MESO',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:87',
    File_name: 'MESO.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'OV',
    Sample_size: 'clinical_stage:576; igcccg_stage:--; masaoka_stage:--; pathologic_stage:--',
    File_name: 'OV.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PAAD',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:183',
    File_name: 'PAAD.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PRAD',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:--',
    File_name: 'PRAD.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'READ',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:161',
    File_name: 'READ.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'SKCM',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:432',
    File_name: 'SKCM.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'STAD',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:419',
    File_name: 'STAD.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'TGCT',
    Sample_size: 'clinical_stage:125; igcccg_stage:43; masaoka_stage:--; pathologic_stage:127',
    File_name: 'TGCT.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THCA',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:--; pathologic_stage:501',
    File_name: 'THCA.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THYM',
    Sample_size: 'clinical_stage:--; igcccg_stage:--; masaoka_stage:84; pathologic_stage:--',
    File_name: 'THYM.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCEC',
    Sample_size: 'clinical_stage:548; igcccg_stage:--; masaoka_stage:--; pathologic_stage:--',
    File_name: 'UCEC.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCS',
    Sample_size: 'clinical_stage:57; igcccg_stage:--; masaoka_stage:--; pathologic_stage:--',
    File_name: 'UCS.stage.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UVM',
    Sample_size: 'clinical_stage:80; igcccg_stage:--; masaoka_stage:--; pathologic_stage:79',
    File_name: 'UVM.stage.tsv.gz',
    download: 'Download',
  },
];
