export default [
  {
    Cancer_type: 'ACC',
    Sample_size: 'DFI:51; DSS:88; OS:92; PFS:92',
    File_name: 'ACC.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BLCA',
    Sample_size: 'DFI:163; DSS:354; OS:410; PFS:412',
    File_name: 'BLCA.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'BRCA',
    Sample_size: 'DFI:912; DSS:1028; OS:1096; PFS:1096',
    File_name: 'BRCA.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CESC',
    Sample_size: 'DFI:171; DSS:290; OS:307; PFS:307',
    File_name: 'CESC.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'CHOL',
    Sample_size: 'DFI:25; DSS:41; OS:45; PFS:45',
    File_name: 'CHOL.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'COAD',
    Sample_size: 'DFI:182; DSS:420; OS:457; PFS:458',
    File_name: 'COAD.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'DLBC',
    Sample_size: 'DFI:25; DSS:43; OS:48; PFS:48',
    File_name: 'DLBC.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'ESCA',
    Sample_size: 'DFI:73; DSS:159; OS:185; PFS:185',
    File_name: 'ESCA.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'GBM',
    Sample_size: 'DFI:3; DSS:548; OS:592; PFS:596',
    File_name: 'GBM.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'HNSC',
    Sample_size: 'DFI:122; DSS:434; OS:526; PFS:527',
    File_name: 'HNSC.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KICH',
    Sample_size: 'DFI:70; DSS:109; OS:112; PFS:112',
    File_name: 'KICH.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRC',
    Sample_size: 'DFI:112; DSS:470; OS:537; PFS:535',
    File_name: 'KIRC.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'KIRP',
    Sample_size: 'DFI:177; DSS:274; OS:290; PFS:289',
    File_name: 'KIRP.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LAML',
    Sample_size: 'DFI:0; DSS:0; OS:188; PFS:0',
    File_name: 'LAML.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LGG',
    Sample_size: 'DFI:132; DSS:502; OS:514; PFS:514',
    File_name: 'LGG.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LIHC',
    Sample_size: 'DFI:282; DSS:324; OS:376; PFS:376',
    File_name: 'LIHC.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUAD',
    Sample_size: 'DFI:278; DSS:442; OS:513; PFS:513',
    File_name: 'LUAD.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'LUSC',
    Sample_size: 'DFI:252; DSS:372; OS:498; PFS:499',
    File_name: 'LUSC.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'MESO',
    Sample_size: 'DFI:8; DSS:56; OS:86; PFS:84',
    File_name: 'MESO.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'OV',
    Sample_size: 'DFI:277; DSS:535; OS:576; PFS:582',
    File_name: 'OV.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PAAD',
    Sample_size: 'DFI:58; DSS:164; OS:185; PFS:185',
    File_name: 'PAAD.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PCPG',
    Sample_size: 'DFI:159; DSS:177; OS:179; PFS:179',
    File_name: 'PCPG.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'PRAD',
    Sample_size: 'DFI:337; DSS:495; OS:499; PFS:500',
    File_name: 'PRAD.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'READ',
    Sample_size: 'DFI:47; DSS:159; OS:169; PFS:170',
    File_name: 'READ.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'SARC',
    Sample_size: 'DFI:146; DSS:243; OS:261; PFS:261',
    File_name: 'SARC.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'SKCM',
    Sample_size: 'DFI:0; DSS:429; OS:461; PFS:456',
    File_name: 'SKCM.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'STAD',
    Sample_size: 'DFI:225; DSS:368; OS:436; PFS:439',
    File_name: 'STAD.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'TGCT',
    Sample_size: 'DFI:104; DSS:133; OS:134; PFS:134',
    File_name: 'TGCT.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THCA',
    Sample_size: 'DFI:354; DSS:498; OS:503; PFS:507',
    File_name: 'THCA.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'THYM',
    Sample_size: 'DFI:0; DSS:118; OS:123; PFS:123',
    File_name: 'THYM.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCEC',
    Sample_size: 'DFI:403; DSS:516; OS:547; PFS:547',
    File_name: 'UCEC.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UCS',
    Sample_size: 'DFI:25; DSS:53; OS:57; PFS:57',
    File_name: 'UCS.survival.tsv.gz',
    download: 'Download',
  },
  {
    Cancer_type: 'UVM',
    Sample_size: 'DFI:0; DSS:78; OS:80; PFS:79',
    File_name: 'UVM.survival.tsv.gz',
    download: 'Download',
  },
];
